training:
  epochs: 2
  batch_size: 16
  learning_rate: 5e-4
  warmup_ratio: 0.1
  weight_decay: 0.01
  save_steps: 20
  eval_steps: 20
  logging_steps: 10
  max_train_samples: 80
  max_eval_samples: 20
