training:
  epochs: 5
  batch_size: 16
  learning_rate: 3e-5
  warmup_ratio: 0.1
  weight_decay: 0.01
  save_steps: 50
  eval_steps: 50
  logging_steps: 10
  max_train_samples: 24  # Usaremos 80% para entrenamiento
  max_eval_samples: 6    # Y 20% para validación
